name: Gh-Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 # Only works with v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.27.4'
      - run: flutter --version
      - run: flutter pub get
      - run: flutter build web --release --base-href="/my_portfolio/"
      - uses: bluefireteam/flutter-gh-pages@v8
        with:
          baseHref: /my_portfolio/
